spring:
  datasource:
    driver-class-name: org.postgresql.Driver  # 数据库驱动类名
    url: jdbc:postgresql://106.54.9.19:5432/excel_for_english  # 数据库连接 URL
    username: postgres  # 数据库用户名
    password: biaoge666  # 数据库密码
    hikari:
      maximum-pool-size: 20  # 连接池最大连接数
      minimum-idle: 5  # 连接池最小空闲连接数
      connection-timeout: 30000  # 连接超时时间，30秒
      idle-timeout: 600000  # 空闲连接超时时间，10分钟
      max-lifetime: 1800000  # 连接最大生存时间，30分钟

  redis:
    host: 106.54.9.19
    port: 6379
    password: biaoge666
    database: 0
server:
  port: 9999

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ledger.es_test1.domain
  mapper-locations: classpath*:mapper/*.xml


common:
  path: "D:\\360TEST\\"
  fileName: "ledger.xlsx"
  sheetName: "EnglishWord"



